myadd:	main.1.o myadd.o
	gcc	-Wall -ansi -pedantic main.1.o myadd.o -o myadd
main.1.o:	main.1.c
	gcc -c -Wall -ansi -pedantic main.1.c -o main.1.o
myadd.o:	myadd.c
	gcc -c -Wall -ansi -pedantic myadd.c -o myadd.o
